### ISSUE TITLE
Most_occuring_element_in_array.cpp

### ISSUE THREAD

**Issue by Prajakta102** [Rasesh2005/CP_Snippets#13]

**Comment by Rasesh2005** [comment]
This is the 3rd time you have tried making a Pull Request, Please Follow Guidelines this Time, Else I will have to mark your Pull Request Invalid. Only 1 File Allowed Remove all Exe Files, make a function packed program And Follow The Code structure as given in Contribution.md

**Comment by Prajakta102** [comment]
This is my first hacktoberfest and it's my first open source contribution so it's getting really confusing for me I'm extremely sorry if I'm bothering you.
I will make proper changes in it.

**Comment by Rasesh2005** [comment]
Yeah Sure I have No issues In Telling Your Mistakes But You were repeating your mistakes, and that bothered me .. and beware that if u get invalid/spam 2 times u get permanently banned from hacktoberfest, so always read contribution.md of a repo if there exists one
