### ISSUE TITLE
Code to find the absolute difference between two diagonals of a square matrix

### ISSUE THREAD

**Issue by Deadeye001** [Rasesh2005/CP_Snippets#27]

**Comment by Rasesh2005** [comment]
Describe it in more detail please??? Not enough detail for me to understand

**Comment by Deadeye001** [comment]
> Describe it in more detail please??? Not enough detail for me to understand

The code basically computes the difference between the sum of the 2 diagonals(left diagonal & right diagonal) of a square matrix of n rows and columns

**Comment by Rasesh2005** [comment]
OK You need to include example in Description with how it works, I am assigning u the issue
