### ISSUE TITLE
SwapTwoVariables.cpp

### ISSUE THREAD

**Issue by vishaaal** [Rasesh2005/CP_Snippets#3]
In this C++ Programming, we will perform Swapping of 2 Variables using 3rd Variable in C++. The third variable will act as a temporary variable to perform the swapping.

**Comment by Rasesh2005** [comment]
Ohk You Can make Pull Request, make sure to be precise with following the rules in [https://github.com/Rasesh2005/CP_Snippets/blob/main/Contribution.md](Contribution) page of the repository ;)
