### ISSUE TITLE
Adding a program to implement stack operations using Linked Lists in C

### ISSUE THREAD

**Issue by mnaiwrit52** [Rasesh2005/CP_Snippets#36]
# What is Stack? 💻 
## A Stack is a linear data structure that follows the LIFO (Last-In-First-Out) principle.
# What does the program do? 🤔 
## This program will do the following tasks:
- 🔼 Push - Insert element at the **top** of the list  
- 🔽 Pop - Delete element at the **top** of the list
- 🖨️ Display Stack Top - Display the element on the top of stack
- ⛔ Exit - Quit the user defined loop

**Comment by mnaiwrit52** [comment]
Please assign

**Comment by Rasesh2005** [comment]
Ohk Make A Data Structures Folder in whichever language You are going to implement stack and put your implementation in that folder and then send me a PR, I approve Your Issue
