### ISSUE TITLE
Adding C++ program to reverse a string.

### ISSUE THREAD

**Issue by VaibhavMogha** [Rasesh2005/CP_Snippets#37]
Hey!
I want to add a C++ program to check input is palindrome or not.
Please assign me this.
Thank you!

**Comment by Rasesh2005** [comment]
Go ahead, make a PR

**Comment by Rasesh2005** [comment]
But a cpp file already exists for palindrome, you can try with other languages or select a different topic

**Comment by Rasesh2005** [comment]
Tell me whatever your choice will be

**Comment by VaibhavMogha** [comment]
> Tell me whatever your choice will be

I will make a program to reverse a string in C++.
Please assign it to me.
Thank you!

**Comment by Rasesh2005** [comment]
Assigned
