### ISSUE TITLE
find middle element in linked list file name:Find_Middle_element.cpp Language:cpp Approach:to find the middle element in linked list :-1.fistly find the lenght of linked list (number of nodes in linked list)  2.traverse till half the length  3.return the next element

### ISSUE THREAD

**Issue by Prajakta102** [Rasesh2005/CP_Snippets#8]

**Comment by Rasesh2005** [comment]
What will be the filename? And what data structures will u use for linked list? Which language? State these information and i will assign you the task then u can Send Pull request

**Comment by Rasesh2005** [comment]
Name the file MiddleElementInLinkedList.cpp and place it inside cpp folder and make a pr
